language: python
python:
 - "3.6.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

script: 
  - pytest 
  - coverage run test_order.py
  - cov=app


after_success:
  - coveralls