language: python
python:
 - "3.6.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

script: 
  - pytest test_order.py --cover-package=app

after_success:
  - coveralls